- name: ensure mysql is running (this is idempotent so safe)
  service: name=mysql state=started
  tags:
    - db
    - wordpress

- name: create wordpress DB
  mysql_db: name=wordpress state=present encoding=utf8
  register: dbschema
  tags:
    - db
    - wordpress

- name: create wordpress DB user
  mysql_user: name={{wordpress_db_user}} password={{wordpress_db_password}} priv=wordpress.*:ALL state=present
  tags:
    - db
    - wordpress

- name: install PHP
  apt: pkg={{item}} state=present
  with_items:
    - php5-gd
    - libssh2-php
    - libapache2-mod-php5
    - php5-mysql
  tags:
    - php
    - wordpress  

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  tags:
    - wordpress    

- name: Download wordpress
  get_url: url=http://wordpress.org/latest.tar.gz dest=/tmp/latest.tar.gz
  tags:
    - wordpress

- name: Extract wordpress
  command: "tar xzvf /tmp/latest.tar.gz"
  tags:
    - wordpress

- name: Extract wordpress
  command: "rsync -avP /tmp/wordpress/ /var/www/html/"
  tags:
    - wordpress

- name: set permissions for wordpress
  file: path=/var/www/html/ mode=777
  tags:
    - wordpress

- name: ensure tomcat context directory exists
  file: path=/var/www/html/ state=directory owner=ubuntu group="www-data"
  tags:
    - wordpress  

- name: Wordpress config
  template: src={{item}} dest=/var/www/html/{{ item }} mode=0666
  with_items:
    - "wp-config.php"
    - ".htaccess"
  tags:
    - wordpress  
    - config

- name: Remove existing index.html
  command: "rm /var/www/html/index.html"
  tags:
    - wordpress
