- name: Add entries for host into hosts file
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line="127.0.0.1 localhost {{ homepage_hostname | default('') }} ala.vagrant.dev ala demo.vagrant1.ala.org.au vagrant1.ala.org.au" owner=root group=root mode=0644

- include: ../../apache_vhost/tasks/main.yml hostname='{{ homepage_hostname }}'
  tags:
    - homepage

- name: Ensure data directory exists
  file: path=/srv/{{ homepage_hostname }}/www/{{ item }} state=directory owner=root group=root
  with_items:
    - "commonui-bs2"
    - "commonui-bs3"
  tags:
    - homepage

- name: Copy welcome page (Debian)
  template: src={{item}} dest=/srv/{{ homepage_hostname }}/www/{{ item }} mode=0666
  with_items:
    - ".htaccess"
    - "index.html"
    - "404.html"
    - "500.html"
    - "503.html"
    - "commonui-bs2/banner.html"
    - "commonui-bs2/footer.html"
    - "commonui-bs3/banner.html"
    - "commonui-bs3/footer.html"
  tags:
    - homepage
    - html